import "./globals.css";
import { Suspense } from "react";
import { Inter } from "next/font/google";
//components
import Loader from "@/components";
//////////////////////////////////////////////////

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
        <title>Car Dealer</title>
      </head>
      <body className={inter.className}>
        <Suspense fallback={<Loader />}>
          {children}
        </Suspense>
      </body>
  </html>
  );
}
