import "./globals.css";
import { Suspense } from "react";
import { Inter } from "next/font/google";
//components
import Loader from "@/components";
//////////////////////////////////////////////////

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Suspense fallback={<Loader />}>
          { children }
        </Suspense>
      </body>
    </html>
  );
}
